name: Yugen.Toolkit.Uwp.Mvvm/Build, Pack and Publish Nuget
on:
  push:
    branches:    
      - main   

jobs:   
  build_pack_publish:
    runs-on: windows-latest

    env:
      SOLUTION_FILE: Yugen.Toolkit.sln
      CONFIGURATION: Release
      PROJECT_FOLDER: Yugen.Toolkit.Uwp.Mvvm
      PROJECT_FILE: Yugen.Toolkit.Uwp.Mvvm.csproj
      NUGET_SOURCE_URL: https://api.nuget.org/v3/index.json
      GH_NUGET_SOURCE_NAME: GitHub
      GH_NUGET_SOURCE_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

    steps:
    - uses: actions/checkout@v1   

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_KEY }}

    - name: Restore dependencies
      run: nuget restore $env:SOLUTION_FILE
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1      

    - name: MSBuild Build
      run: msbuild $env:PROJECT_FOLDER\$env:PROJECT_FILE /p:Configuration=$env:CONFIGURATION

    - name: MSBuild Pack
      run: msbuild $env:PROJECT_FOLDER\$env:PROJECT_FILE /p:Configuration=$env:CONFIGURATION /t:pack 

    - name: Nuget Push
      run: nuget push $env:PROJECT_FOLDER\bin\$env:CONFIGURATION\*.nupkg -Source $env:NUGET_SOURCE_URL
      continue-on-error: true
    
    - name: GH Nuget Add Source
      run: nuget source Add -Name $env:GH_NUGET_SOURCE_NAME -Source $env:GH_NUGET_SOURCE_URL -UserName ${{ github.repository_owner }} -Password ${{ secrets.PACKAGES_TOKEN }}
      
    - name: GH Nuget SetAPIKey
      run: nuget setApiKey ${{ secrets.PACKAGES_TOKEN }} -Source $env:GH_NUGET_SOURCE_NAME

    - name: GH Nuget Push
      run: nuget push $env:PROJECT_FOLDER\bin\$env:CONFIGURATION\*.nupkg -Source $env:GH_NUGET_SOURCE_NAME
